name: Arkama-Grades
api-version: 1.16
version: "5.0.0"
main: fr.guigui205.arkama.ArkaGrades
author: Guigui205 & DaveUltra & Timoreo (spelling by EnkiGaming)
commands:
  setgrade:
    description: "permet de se tp a un emplacement personnel"
    permission: "ArkaGrade.setgrade"