name: Arkama-Wands
api-version: 1.16
version: "5.0.0"
main: fr.guigui205.arkama.ArkaWands
author: Guigui205 & DaveUltra & Timoreo (spelling by EnkiGaming)
commands:
  magie:
    description: "donne toutes les baguettes du serveur"
    permission: "ArkaWand.magie"
permissions:
  ArkaWand.magie:
    default: op
