name: Arkama
api-version: 1.16
version: "5.0.0"
author: Guigui205 & DaveUltra & Timoreo (spelling by EnkiGaming)
main: fr.mediapi.arkama.Arkama
database: true
commands:
  warp:
    description: "en test"
  time:
    description: "Temps en heure"
    permission: Arkama.time
  sun:
    description: "Mettre le beau temps"
    permission: Arkama.sun
    usage: "Usage: /<command>"
  rain:
    description: "Mettre la pluie"
    permission: Arkama.rain
    usage: "Usage: /<command>"
  thunder:
    description: "Mettre l'orage"
    permission: Arkama.thunder
    usage: "Usage: /<command>"
  weather:
    description: "Changer le temps du monde actif"
    permission: Arkama.weather
    usage: "Usage: /<command>"
  craft:
    description: "Fais tes crafts"
    permission: Arkama.craft
  clear:
    description: "Nettoie ton inventaire"
    permission: Arkama.clear
    usage: "Usage: /<command>"
  magie:
    description: "En développement"
    permission: Arkama.magie
  nick:
    description: "Te renommer"
    permission: Arkama.nick
    usage: "Usage: /<command> [nom]"
  invsee:
    description: "Voir et modifier l'inventaire des autres joueurs"
    permission: Arkama.invsee
    usage: "Usage: /<command> [username]"
  tp:
    description: "Téléport"
    permission: Arkama.tp
    usage: "Usage: /<command> [coordonnées]"
  hub:
    description: "Définit un hub"
    permission: Arkama.hub
  setgrade:
    description: "Définit un grade"
    permission: Arkama.grade
  heal:
    description: "Met ta vie à 100%"
    permission: Arkama.heal
  feed:
    description: "Met ta faim à 100%"
    permission: Arkama.feed
  rl:
    description: "Redémarrage du serveur"
    permission: Arkama.rl
  vanish:
    description: "Et les taches s'évanouish !"
    permission: Arkama.vanish
  enchant:
    description: "Enchantement"
    permission: Arkama.enchant
  kick:
    description: "A TON AVIS CONNARD"
    usage: "Usage: /<command> [username]"
  msg:
    description: "Envoyer un message privé"
    permission: arkama.msg
    usage: "Usage: /<command> [username]"
  r:
    description: "Renvoyer un message au dernier correspondant"
    permission: Arkama.msg
    usage: "Usage: /<command> [username]"
  hat:
    description: "En test"
    permission: Arkama.hat
  money:
    description: "Te donne de l'argent"
    permission: Arkama.money
  ville:
    desription: "Ne marche pas"
  speed:
    description: "En test"
  kit:
    description: "En test"
  kill:
    description: "En test"
  rename:
    description: "En test"
  murder:
    description: "Commande principale pour le murder"
  ctf:
    description: "Commande principale du CTF"
  setctf:
    description: "Définir le CTF"
  world:
    description: "Commande principale pour xXx_Mutiverse_xXx"
    permission: Arkama.world

permissions:
  Arkama.gm:
    default: op
  Arkama.time:
    default: op
  Arkama.sun:
    default: op
  Arkama.rain:
    default: op
  Arkama.thunder:
    default: op
  Arkama.weather:
    default: op
  Arkama.craft:
    default: op
  Arkama.clear:
    default: op
  Arkama.magie:
    default: op
  Arkama.nick:
    default: op
  Arkama.invsee:
    default: op
  Arkama.tp:
    default: op
  Arkama.hub:
    default: true
  Arkama.sethub:
    default: op
  Arkama.grade:
    default: op
  Arkama.heal:
    default: op
  Arkama.feed:
    default: op
  Arkama.rl:
    default: op
  Arkama.vanish:
    default: op
  Arkama.kick:
    default: op
  Arkama.enchant:
    default: op
  Arkama.msg:
    default: true
  Arkama.hat:
    default: op
  Arkama.kit:
    default: true
  Arkama.rename:
    default: op
  Arkama.world:
    default: true
